GET http://localhost:8080/users/1
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5YWM5NmFjOS04ODU0LTQxZTYtYWRkYi01MzcwMzhmYzNlZTIiLCJjcmVhdGVkIjoxNTkyNzExNjkzMjQ0LCJleHAiOjE1OTI3MTg4OTN9.2aDx1AJ8z5h2Fx3tvzpZeM2WPEHbE9mr6b-Ygz4oNEyOnafB29qg_Bb-Re1rudLAZ24A9GTyu9Y1YGS83UIfjw

###
GET http://localhost:8080/users/current
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5YWM5NmFjOS04ODU0LTQxZTYtYWRkYi01MzcwMzhmYzNlZTIiLCJjcmVhdGVkIjoxNTkyNzExNjkzMjQ0LCJleHAiOjE1OTI3MTg4OTN9.2aDx1AJ8z5h2Fx3tvzpZeM2WPEHbE9mr6b-Ygz4oNEyOnafB29qg_Bb-Re1rudLAZ24A9GTyu9Y1YGS83UIfjw

### 登陆
POST http://localhost:8080/login?username=admin&password=admin

### 登出
GET http://localhost:8080/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5YWM5NmFjOS04ODU0LTQxZTYtYWRkYi01MzcwMzhmYzNlZTIiLCJjcmVhdGVkIjoxNTkyNzExNjkzMjQ0LCJleHAiOjE1OTI3MTg4OTN9.2aDx1AJ8z5h2Fx3tvzpZeM2WPEHbE9mr6b-Ygz4oNEyOnafB29qg_Bb-Re1rudLAZ24A9GTyu9Y1YGS83UIfjw
