server:
  port: 7070

spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/boot_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.muqing.model
  mapper-locations: classpath:/mybatis-mappers/* # MyBatis的mapper.xml的路径配置
  configuration:
    mapUnderscoreToCamelCase: true

# 自定义jwt key
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mySecret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24)
#  tokenHead: Bearer  #JWT负载中拿到开头

#token配置
token:
  expiration: 7200 #token过期限秒数(60*60*24)
  jwtSecret: mySecret:) #私钥